### ISSUE TITLE
Create crystal twin on the grid

### ISSUE THREAD

**Issue by ken-de-moor** [crystaluniverse/crystaltwin#1]
For the first version, we simply need to set up the technology stack that enables us to do these following things.

Working out all these features can be done in different user stories. First we need to make sure we can host and use everything on the grid. For this we want to implement one example proof of concept implementation for every step.

## Implement technology stack
- [ ] Make a crystal based project and host on the grid
- [ ] Add Python/jsng as subprocess, seamless, to the crystal based project and host on the grid https://github.com/crystaluniverse/crystaltwin/issues/2
- [ ] Add basic API and host on the grid
    - [ ] Messaging ( chat ) https://github.com/crystaluniverse/crystaltwin/issues/3
    - [ ] Interaction with wallets https://github.com/crystaluniverse/crystaltwin/issues/4
- [ ] Interact with wallets ( dash, digitbyte, tft, btc, eth, vlm ) using rpc jsng subprocess and host on the grid https://github.com/crystaluniverse/crystaltwin/issues/5

![image](https://user-images.githubusercontent.com/59569757/91721624-5c57c100-eb99-11ea-8d28-f30f3783a228.png)
